# Generated by Django 5.1.2 on 2024-10-16 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TRC', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trancion',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trancion',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trancion',
            name='descripition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trancion',
            name='user_TRC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trancion',
            name='pain',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
