# Generated by Django 5.1.2 on 2024-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TRC', '0003_remove_trancion_pain_trancion_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trancion',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
