# Generated by Django 5.1.2 on 2024-10-25 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TRC', '0004_alter_trancion_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trancion',
            name='user_TRC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trancionsforuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
